### ISSUE TITLE
[init-couchdb] Error

### ISSUE THREAD

**Issue by LinG955** [apache/openwhisk-devtools#330] opened 2021-04-09 07:58 UTC
I want to install openwhisk-devtools in the CentOS7, when I run `make quick-start`, it was Error. The logs as follow:
```bash
[root@localhost docker-compose]# make quick-start
Unpacking tarball.
downloading the CLI tool ... 
downloading cli for linux
nightly: Pulling from openwhisk/controller
Digest: sha256:66691357d86094d27bc8fe9d5cd85b18c1b081640151e4a37d41bb52368b0977
Status: Image is up to date for openwhisk/controller:nightly
docker.io/openwhisk/controller:nightly
nightly: Pulling from openwhisk/nodejs6action
Digest: sha256:f36f93c2ce7a8c98b7a966e520e0e8eecc8ddeec44471e6ae76b433fc16640a7
Status: Image is up to date for openwhisk/nodejs6action:nightly
docker.io/openwhisk/nodejs6action:nightly
nightly: Pulling from openwhisk/dockerskeleton
Digest: sha256:54cfbac098f0c0911db7af5557ce19b9534ad381737742abf160e077c04fb9d4
Status: Image is up to date for openwhisk/dockerskeleton:nightly
docker.io/openwhisk/dockerskeleton:nightly
pulling the docker images short list... 
nightly: Pulling from openwhisk/invoker
Digest: sha256:0cfb488640364c1d549d47c0fe7b8012f4e79210f00c55f0b5698ec3eb311781
Status: Image is up to date for openwhisk/invoker:nightly
docker.io/openwhisk/invoker:nightly
host ip address: 192.168.68.132
checking required ports ... 
 ... OK
  ... preparing api-gateway configuration
pinging minio...
Starting openwhisk_minio_1 ... done
 ... OK
generating server certificate request
generating self-signed password-less server certificate
Signature ok
subject=/C=US/ST=NY/L=Yorktown/O=OpenWhisk/CN=192.168.68.132
Getting Private key
generate keystore
Waiting till all containers are powered up... 
Starting openwhisk_db_1 ... 
Starting openwhisk_db_1        ... done
Starting openwhisk_zookeeper_1 ... done
Starting openwhisk_redis_1     ... done
Starting openwhisk_kafka_1     ... done
Starting openwhisk_invoker_1         ... done
Starting openwhisk_kafka-rest_1 ... done
Starting openwhisk_controller_1      ... done
Starting openwhisk_kafka-topics-ui_1 ... done
Starting openwhisk_apigateway_1      ... done
 ... OK: all containers up!
waiting for the database to come up ... on 192.168.68.132
initializing the database ... on 192.168.68.132
Setting up db using ansible container....
 [WARNING]: Unable to parse /openwhisk/ansible/environments/local as an inventory source

 [WARNING]: No inventory was parsed, only implicit localhost is available

 [WARNING]: Could not match supplied host pattern, ignoring: all

 [WARNING]: provided hosts list is empty, only localhost is available


PLAY [localhost] ****************************************************************************************************************************************************************************

TASK [Gathering Facts] **********************************************************************************************************************************************************************
Friday 09 April 2021  15:25:26 +0000 (0:00:00.214)       0:00:00.214 ********** 
ok: [localhost]

TASK [gen hosts if 'local' env is used] *****************************************************************************************************************************************************
Friday 09 April 2021  15:25:49 +0000 (0:00:23.340)       0:00:23.555 ********** 
changed: [localhost -> localhost]

TASK [find the ip of docker-machine] ********************************************************************************************************************************************************
Friday 09 April 2021  15:25:51 +0000 (0:00:02.150)       0:00:25.705 ********** 
skipping: [localhost]

TASK [get the docker-machine ip] ************************************************************************************************************************************************************
Friday 09 April 2021  15:25:51 +0000 (0:00:00.105)       0:00:25.811 ********** 
skipping: [localhost]

TASK [gen hosts for docker-machine] *********************************************************************************************************************************************************
Friday 09 April 2021  15:25:51 +0000 (0:00:00.104)       0:00:25.916 ********** 
skipping: [localhost]

TASK [gen hosts for Jenkins] ****************************************************************************************************************************************************************
Friday 09 April 2021  15:25:52 +0000 (0:00:00.167)       0:00:26.083 ********** 
skipping: [localhost]

TASK [check if db_local.ini exists?] ********************************************************************************************************************************************************
Friday 09 April 2021  15:25:52 +0000 (0:00:00.119)       0:00:26.203 ********** 
ok: [localhost]

TASK [prepare db_local.ini] *****************************************************************************************************************************************************************
Friday 09 April 2021  15:25:52 +0000 (0:00:00.502)       0:00:26.705 ********** 
changed: [localhost -> localhost]

TASK [gen untrusted server certificate for host] ********************************************************************************************************************************************
Friday 09 April 2021  15:25:53 +0000 (0:00:00.815)       0:00:27.520 ********** 
changed: [localhost -> localhost]

TASK [gen untrusted client certificate for host] ********************************************************************************************************************************************
Friday 09 April 2021  15:25:56 +0000 (0:00:02.805)       0:00:30.326 ********** 
changed: [localhost -> localhost]

TASK [clean up old kafka keystore] **********************************************************************************************************************************************************
Friday 09 April 2021  15:25:59 +0000 (0:00:03.115)       0:00:33.441 ********** 
skipping: [localhost]

TASK [ensure kafka files directory exists] **************************************************************************************************************************************************
Friday 09 April 2021  15:25:59 +0000 (0:00:00.153)       0:00:33.594 ********** 
skipping: [localhost]

TASK [generate kafka certificates] **********************************************************************************************************************************************************
Friday 09 April 2021  15:25:59 +0000 (0:00:00.208)       0:00:33.803 ********** 
skipping: [localhost]

TASK [ensure controller files directory exists] *********************************************************************************************************************************************
Friday 09 April 2021  15:25:59 +0000 (0:00:00.154)       0:00:33.957 ********** 
fatal: [localhost]: FAILED! => {"failed": true, "msg": "The conditional check 'controller.protocol == 'https'' failed. The error was: {u'protocol': u\"{{ controller_protocol | default('https') }}\", u'extraEnv': u'{{ controller_extraEnv | default({}) }}', u'dir': {u'become': u'{{ controller_dir_become | default(false) }}'}, u'ssl': {u'keystore': {u'password': u'openwhisk', u'name': u'{{ __controller_ssl_keyPrefix }}openwhisk-keystore.p12'}, u'cert': u'{{ __controller_ssl_keyPrefix }}openwhisk-server-cert.pem', u'cn': u'openwhisk-controllers', u'key': u'{{ __controller_ssl_keyPrefix }}openwhisk-server-key.pem', u'keyPrefix': u'{{ __controller_ssl_keyPrefix }}', u'clientAuth': u\"{{ controller_client_auth | default('true') }}\", u'storeFlavor': u'PKCS12'}, u'heap': u\"{{ controller_heap | default('2g') }}\", u'managedFraction': u'{{ controller_managed_fraction | default(1.0 - (controller_blackbox_fraction | default(__controller_blackbox_fraction))) }}', u'entitlement': {u'spi': u\"{{ controller_entitlement_spi | default('') }}\"}, u'instances': u\"{{ groups['controllers'] | length }}\", u'loglevel': u\"{{ controller_loglevel | default(whisk_loglevel) | default('INFO') }}\", u'timeoutFactor': u'{{ controller_timeout_factor | default(2) }}', u'blackboxFraction': u'{{ controller_blackbox_fraction | default(__controller_blackbox_fraction) }}', u'confdir': u'{{ config_root_dir }}/controller', u'authentication': {u'spi': u\"{{ controller_authentication_spi | default('') }}\"}, u'arguments': u\"{{ controller_arguments | default('') }}\", u'timeoutAddon': u\"{{ controller_timeout_addon | default('1 m') }}\", u'basePort': 10001, u'akka': {u'cluster': {u'bindPort': 2551, u'basePort': 8000, u'host': u\"{{ groups['controllers'] | map('extract', hostvars, 'ansible_host') | list }}\", u'seedNodes': u\"{{ groups['controllers'] | map('extract', hostvars, 'ansible_host') | list }}\"}, u'provider': u'cluster'}, u'loadbalancer': {u'spi': u\"{{ controller_loadbalancer_spi | default('') }}\"}}: template error while templating string: expected token ',', got 'second'. String: {{ scheduler_dataManagementService_retryInterval | default(1 second) }}\n\nThe error appears to have been in '/openwhisk/ansible/setup.yml': line 89, column 5, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n  # Generate Controller certificates\n  - name: ensure controller files directory exists\n    ^ here\n"}

The conditional check 'controller.protocol == 'https'' failed. The error
was: {u'protocol': u"{{ controller_protocol | default('https') }}", u'extraEnv':
u'{{ controller_extraEnv | default({}) }}', u'dir': {u'become': u'{{
controller_dir_become | default(false) }}'}, u'ssl': {u'keystore': {u'password':
u'openwhisk', u'name': u'{{ __controller_ssl_keyPrefix }}openwhisk-
keystore.p12'}, u'cert': u'{{ __controller_ssl_keyPrefix }}openwhisk-server-
cert.pem', u'cn': u'openwhisk-controllers', u'key': u'{{
__controller_ssl_keyPrefix }}openwhisk-server-key.pem', u'keyPrefix': u'{{
__controller_ssl_keyPrefix }}', u'clientAuth': u"{{ controller_client_auth |
default('true') }}", u'storeFlavor': u'PKCS12'}, u'heap': u"{{ controller_heap |
default('2g') }}", u'managedFraction': u'{{ controller_managed_fraction |
default(1.0 - (controller_blackbox_fraction |
default(__controller_blackbox_fraction))) }}', u'entitlement': {u'spi': u"{{
controller_entitlement_spi | default('') }}"}, u'instances': u"{{
groups['controllers'] | length }}", u'loglevel': u"{{ controller_loglevel |
default(whisk_loglevel) | default('INFO') }}", u'timeoutFactor': u'{{
controller_timeout_factor | default(2) }}', u'blackboxFraction': u'{{
controller_blackbox_fraction | default(__controller_blackbox_fraction) }}',
u'confdir': u'{{ config_root_dir }}/controller', u'authentication': {u'spi':
u"{{ controller_authentication_spi | default('') }}"}, u'arguments': u"{{
controller_arguments | default('') }}", u'timeoutAddon': u"{{
controller_timeout_addon | default('1 m') }}", u'basePort': 10001, u'akka':
{u'cluster': {u'bindPort': 2551, u'basePort': 8000, u'host': u"{{
groups['controllers'] | map('extract', hostvars, 'ansible_host') | list }}",
u'seedNodes': u"{{ groups['controllers'] | map('extract', hostvars,
'ansible_host') | list }}"}, u'provider': u'cluster'}, u'loadbalancer': {u'spi':
u"{{ controller_loadbalancer_spi | default('') }}"}}: template error while
templating string: expected token ',', got 'second'. String: {{
scheduler_dataManagementService_retryInterval | default(1 second) }}  The error
appears to have been in '/openwhisk/ansible/setup.yml': line 89, column 5, but
may be elsewhere in the file depending on the exact syntax problem.  The
offending line appears to be:    # Generate Controller certificates   - name:
ensure controller files directory exists     ^ here 

PLAY RECAP **********************************************************************************************************************************************************************************
localhost                  : ok=6    changed=4    unreachable=0    failed=1   

Friday 09 April 2021  15:26:00 +0000 (0:00:00.843)       0:00:34.800 ********** 
=============================================================================== 
Gathering Facts --------------------------------------------------------------------------------------------------------------------------------------------------------------------- 23.34s
gen untrusted client certificate for host -------------------------------------------------------------------------------------------------------------------------------------------- 3.12s
gen untrusted server certificate for host -------------------------------------------------------------------------------------------------------------------------------------------- 2.81s
gen hosts if 'local' env is used ----------------------------------------------------------------------------------------------------------------------------------------------------- 2.15s
ensure controller files directory exists --------------------------------------------------------------------------------------------------------------------------------------------- 0.84s
prepare db_local.ini ----------------------------------------------------------------------------------------------------------------------------------------------------------------- 0.82s
check if db_local.ini exists? -------------------------------------------------------------------------------------------------------------------------------------------------------- 0.50s
ensure kafka files directory exists -------------------------------------------------------------------------------------------------------------------------------------------------- 0.21s
gen hosts for docker-machine --------------------------------------------------------------------------------------------------------------------------------------------------------- 0.17s
generate kafka certificates ---------------------------------------------------------------------------------------------------------------------------------------------------------- 0.15s
clean up old kafka keystore ---------------------------------------------------------------------------------------------------------------------------------------------------------- 0.15s
gen hosts for Jenkins ---------------------------------------------------------------------------------------------------------------------------------------------------------------- 0.12s
find the ip of docker-machine -------------------------------------------------------------------------------------------------------------------------------------------------------- 0.11s
get the docker-machine ip ------------------------------------------------------------------------------------------------------------------------------------------------------------ 0.11s
make: *** [init-couchdb] Error 2
[root@localhost docker-compose]# 
```

**Comment by rabbah** [comment] 2021-04-10 12:52
@LinG955 if you don't explicitly need to use docker-compose please consider using the standalone stack instead 
https://github.com/apache/openwhisk#quick-start

**Comment by rabbah** [comment] 2021-04-10 12:53
Closing as duplicate of https://github.com/apache/openwhisk-devtools/issues/329.

**Closed by rabbah** 2021-04-10 12:53 UTC
