### ISSUE TITLE
incorrect filenames in docker-compose/Makefile

### ISSUE THREAD

**Issue by kuwii** [apache/openwhisk-devtools#306] opened 2019-11-29 06:45 UTC
Got error below when running `make add-catalog`:

```
/bin/sh: /applications/openwhisk/openwhisk-devtools/docker-compose/openwhisk-catalog/packages/installCatalogUsingWskDeploy.sh: No such file or directory
make: *** [init-catalog] Error 127
```

It happens because the actual file name in `openwhisk-catalog/packages` is `installCatalogUsingWskdeploy.sh`, not `installCatalogUsingWskDeploy.sh`. Letter `D` is lowercase.

Also, when running:

```
make create-provider-alarms
make create-provider-kafka
make create-provider-cloudant
```

Name of the related script should be `installCatalog.sh`, not `installCatalogUsingWskDeploy.sh`.

**Comment by dyllandry** [comment] 2020-10-07 14:32
I created a PR https://github.com/apache/openwhisk-catalog/pull/316 in the repo that contains this file. I figured the problem is with them since the file name here follows consistent camel case but over there it's named with inconsistent camel case.

**Comment by rabbah** [comment] 2020-10-07 14:48
Using github search there are several locations that use existing name:
https://github.com/search?q=installCatalogUsingWskdeploy.sh&type=code

I wonder if fixing the error here is better.

**Comment by dyllandry** [comment] 2020-10-07 15:45
It looks like a lot of results in your search clone this repo's main branch. If that PR was approved and it got merged, it would immediately break each of those projects until they were updated with the new file name.

Yeah, I think _fixing_ it here to the inconsistently cased camel case name is a lesser of the two evils.

**Closed** 2021-04-11 19:19 UTC
